#!/usr/bin/env bash

set -e

cd /opt/nodemcu-firmware
BRANCH="$(git rev-parse --abbrev-ref HEAD | sed -r 's/[\/\\]+/_/g')"

cd /opt

case "$BRANCH" in
 dev-esp32) ./build-esp32 ;;
         *) ./build-esp8266 ;;
esac

