#!/usr/bin/env bash

set -e

cd /opt/nodemcu-firmware

# Basically revert windows lineends. Only needed if checkout is done under windows.
git submodule foreach --recursive git checkout .
 
make menuconfig
