#!/usr/bin/env bash

set -e

cd /opt/nodemcu-firmware

# Basically revert windows lineends. Only needed if checkout is done under windows.
if grep $'\r' .gitmodules > /dev/null; then
  git submodule foreach --recursive git checkout .
fi

make menuconfig
