#!/usr/bin/env bash

set -e

cd /opt/nodemcu-firmware

./sdk/esp32-esp-idf/install.sh
. ./sdk/esp32-esp-idf/export.sh

# checkout submodules again as Git may insert "wrong" newlines if you checkout submodules on Windows.
if grep $'\r' .gitmodules > /dev/null; then
  git submodule foreach --recursive git checkout .
fi

make menuconfig
