#!/usr/bin/env bash

set -e

# Config options you may pass via Docker like so 'docker run -e "<option>=<value>"':
# - IMAGE_NAME=<name>, define a static name for your .img files

cd /opt/nodemcu-firmware

if [ ! -x luac.cross -a !  -x luac.cross.int ]; then
  echo Error: No cross compiler found. You need to build the firmeware first.
  exit -1
fi

export BUILD_DATE
BUILD_DATE="$(date "+%Y%m%d-%H%M")"
LUA_FILES=$(find ../lua -iname "*.lua")
echo Adding files: ${LUA_FILES}

if [ -z "$IMAGE_NAME" ]; then
  IMAGE_NAME="${BUILD_DATE}"
fi

# make a float LFS image if available
if [ -x luac.cross ]; then
  FILENAME=LFS_float_"${IMAGE_NAME}".img
  echo creating ${FILENAME}
  find ../lua -iname "*.lua" -exec ./luac.cross -f -o ../lua/"${FILENAME}" {} +
fi

# make an int LFS image if available
if [ -x luac.cross.int ]; then
  FILENAME=LFS_integer_"${IMAGE_NAME}".img
  echo creating ${FILENAME}
  find ../lua -iname "*.lua" -exec ./luac.cross.int -f -o ../lua/"${FILENAME}" {} +
fi

